sudo: false

language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '4'

before_install:
  - npm i -g coveralls
  - npm i -g npm@^2.0.0

before_script:
  - npm prune

script:
  - npm run lint
  - npm run test:coverage
  - npm run coverage:check
  - npm run build

after_success:
  - npm run coverage:report
  - npm run coverage:coveralls
  - npm run semantic-release

branches:
  only:
    - master
